In [26]:
# !python -m pip install pandas


In [27]:
import pandas as pd
import numpy as np

In [28]:
data=pd.read_csv('news.csv')
data.head(5)

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [29]:
y=data['label']
x=data['text']

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)


In [31]:
#Using count vector to covert text in to valuable numerical values
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer, HashingVectorizer
count_vector=CountVectorizer(stop_words='english')
count_vector_train=count_vector.fit_transform(x_train)
count_vector_test=count_vector.transform(x_test)


In [32]:
count_vector_train.shape

(4244, 56801)

In [33]:
y_train.shape

(4244,)

In [34]:
len(count_vector.get_feature_names_out())

56801

In [35]:
count_vector.get_feature_names_out()

array(['00', '000', '0000', ..., 'תתרכז', 'القادمون', 'عربي'],
      dtype=object)

In [36]:
print(count_vector_train)

  (0, 39371)	2
  (0, 29886)	1
  (0, 18756)	1
  (0, 26482)	2
  (0, 12723)	1
  (0, 45820)	1
  (0, 49614)	1
  (0, 35654)	1
  (0, 15846)	2
  (0, 51775)	5
  (0, 23990)	1
  (0, 10533)	4
  (0, 12626)	2
  (0, 39599)	1
  (0, 20249)	1
  (0, 2625)	1
  (0, 13885)	1
  (0, 44932)	1
  (0, 43222)	1
  (0, 21231)	6
  (0, 43952)	6
  (0, 20679)	1
  (0, 45133)	1
  (0, 2586)	1
  (0, 53360)	1
  :	:
  (4243, 36069)	1
  (4243, 55860)	1
  (4243, 52613)	1
  (4243, 52905)	1
  (4243, 52616)	1
  (4243, 53548)	1
  (4243, 55782)	1
  (4243, 26778)	1
  (4243, 47236)	1
  (4243, 15081)	1
  (4243, 4180)	1
  (4243, 39152)	1
  (4243, 9525)	4
  (4243, 51326)	1
  (4243, 54485)	1
  (4243, 24622)	1
  (4243, 17442)	1
  (4243, 10187)	3
  (4243, 33680)	1
  (4243, 25010)	4
  (4243, 54486)	1
  (4243, 30857)	1
  (4243, 16819)	1
  (4243, 53403)	1
  (4243, 17186)	1


In [37]:
print(count_vector_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(count_vector_train,y_train)
prediction=model.predict(count_vector_test)

In [42]:
from sklearn import metrics
Accuracy = metrics.accuracy_score(y_test, prediction)
print("accuracy:   %0.3f" % Accuracy)

cm = metrics.confusion_matrix(y_test, prediction, labels=['FAKE', 'REAL'])

accuracy:   0.889


In [43]:
from sklearn.metrics import classification_report

Report=classification_report(y_test, prediction)
print(Report)

              precision    recall  f1-score   support

        FAKE       0.92      0.85      0.89      1071
        REAL       0.86      0.93      0.89      1020

    accuracy                           0.89      2091
   macro avg       0.89      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091



In [45]:
data["text"][2]

'U.S. Secretary of State John F. Kerry said Monday that he will stop in Paris later this week, amid criticism that no top American officials attended Sunday’s unity march against terrorism.\n\nKerry said he expects to arrive in Paris Thursday evening, as he heads home after a week abroad. He said he will fly to France at the conclusion of a series of meetings scheduled for Thursday in Sofia, Bulgaria. He plans to meet the next day with Foreign Minister Laurent Fabius and President Francois Hollande, then return to Washington.\n\nThe visit by Kerry, who has family and childhood ties to the country and speaks fluent French, could address some of the criticism that the United States snubbed France in its darkest hour in many years.\n\nThe French press on Monday was filled with questions about why neither President Obama nor Kerry attended Sunday’s march, as about 40 leaders of other nations did. Obama was said to have stayed away because his own security needs can be taxing on a country, 

In [51]:
count_vector_train[[2]]

<1x56801 sparse matrix of type '<class 'numpy.int64'>'
	with 155 stored elements in Compressed Sparse Row format>

In [54]:
real_texts=count_vector_train.toarray()
real_texts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [58]:
features=count_vector.get_feature_names_out()

In [59]:
for doc_index, row in enumerate(count_vector_train):
    word_indices = row.nonzero()[1]  # column indices where word count > 0
    words = [features[i] for i in word_indices]
    print(f"Document {doc_index+1} words:", words)

Document 1 words: ['president', 'likely', 'face', 'international', 'crisis', 'shortly', 'taking', 'office', 'donald', 'trump', 'hillary', 'clinton', 'credibility', 'problem', 'foreign', 'affairs', 'defense', 'secretary', 'robert', 'gates', 'said', 'friday', 'senior', 'advocate', 'using', 'military', 'bring', 'ill', 'fated', 'regime', 'change', 'libya', 'failed', 'anticipate', 'chaos', 'follow', 'served', 'presidents', '50', 'years', 'wrote', 'op', 'ed', 'wall', 'street', 'journal', 'failure', 'democrats', 'hung', 'neck', 'bush', '43', 'administration', 'post', 'saddam', 'iraq', 'regarding', 'comes', 'problems', 'league', 'expressed', 'support', 'building', 'mexico', 'torturing', 'suspected', 'terrorists', 'killing', 'families', 'vladimir', 'putin', 'dictatorial', 'leadership', 'hussein', 'nonexistent', 'successes', 'terrorism', 'recently', 'worked', 'george', 'barack', 'obama', 'sized', 'candidates', 'variety', 'global', 'national', 'security', 'issues', 'china', 'north', 'korea', 'ira

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [52]:
model.predict(count_vector_train[[2]])

array(['FAKE'], dtype='<U4')